# Generated by Django 5.2.8 on 2025-12-21 13:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the car', null=True, upload_to=api.models.car_image_upload_path),
        ),
    ]
